[package]
name = "mars_calc"
version = "0.1.0"
authors = ["Quentin DELETTRE <quentin.delettre.neo-soft@externalgcp.ds.airbus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
